on:
  schedule:
    - cron: "* * * 5 *"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: bilibiliHelper
        env:
          BILIBILICOOKIE: ${{secrets.BILIBILICOOKIE}}
          SEVERSCKEY: ${{secrets.SEVERSCKEY}
        run: |
          __main__.py
